_wandb:
    value:
        cli_version: 0.27.2
        e:
            y8v1pscagdsij8w23iyjz27v6i9s88p5:
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "125828067328"
                        used: "49250607104"
                email: raja.valiveti@cogitoslabs.com
                executable: E:\Projects\CND\Semantics\.venv\Scripts\python.exe
                git:
                    commit: 2217d5665ddd069f14d0f8aa3803fa902031a972
                    remote: https://github.com/cogitoslabs/Semantics-Layer.git
                host: Rando
                memory:
                    total: "16582541312"
                os: Windows-11-10.0.26200-SP0
                program: -m pytest.__main__
                python: CPython 3.12.13
                root: E:\Projects\CND\Semantics
                startedAt: "2026-06-17T14:37:34.111589Z"
                writerId: y8v1pscagdsij8w23iyjz27v6i9s88p5
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
            "3":
                - 13
                - 16
            "4": 3.12.13
            "5": 0.27.2
            "6": 4.57.6
            "8":
                - 3
            "12": 0.27.2
            "13": windows-amd64
base_model:
    value: dummy-model
batch_size:
    value: 1
dtype:
    value: bfloat16
eval_interval_tokens:
    value: 50000
learning_rate:
    value: 1e-05
max_seq_len:
    value: 512
ppl_improvement_threshold:
    value: 2
qa_acc_threshold:
    value: 0.55
total_corpus_tokens:
    value: 2000000
warmup_steps:
    value: 1000
